---
title: "Beginner R Workshop"
author: "David Wilkinson"
date: "`r Sys.Date()`"
output: bookdown::gitbook
css: lodestar.css
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: Doi90/Intro_R_Workshop
---

# Preamble

This is the course notes for a *Beginner's R Workshop* run by David Wilkinson. The goal of this workshop is to teach researchers how to use **R** for data analysis. **R** is a free, open-source programming language designed with statistical analysis in mind, and widely used throughout many scientific disciplines. This workshop is designed to provide researchers with a strong foundation in **R**'s fundamentals to facilitate their own research projects.

This course will not assume any prior experience with **R**, but we recommend that attendees with no prior programming experience at all refer to the course material at [Introduction To Programming Concepts](https://nikkirubinstein.gitbooks.io/resguides-introductory-programming-concepts/content/content/welcome-to-coding.html) in advance. We will introduce these concepts during the workshop, but a basic understanding beforehand will help you get to grips with **R** faster. 

This material has been adapted with permission from Research Platforms Services's own [*Introductory R Workshop*](https://nikkirubinstein.gitbooks.io/resguides-introductory-r-workshop/content/) course material.

# Technical Requirements

All attendees will be required to **bring their own laptop and charger**. Tablets and/or Chromebooks (or similar) are not recommended. It can have a Windows, Mac, or Linux operating system, but you must have administrative privileges.

Attendees are also asked to install both [**R**](https://www.r-project.org/) and [**RStudio**](https://www.rstudio.com/) in advance of the workshop. Both **R** and **RStudio** are updated regularly with both new features and bug fixes, so we require attendees to have **R** v3.5 or later, and **RStudio** v1.1.383 or later.